---
title: "3D MDS"
author: "Stephany"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}

#run from console
#rmarkdown::render("3DMDSplot.Rmd")

knitr::opts_chunk$set(echo = TRUE)
#setwd("/run/user/1000/gvfs/sftp:host=imlssherborne/home/sorjuela/RNAseq/Salmon")

library(edgeR)
library(rgl)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(pheatmap)
library(RColorBrewer)
library(genefilter)
library(ggplot2)
library(VennDiagram)

load("DGE_obj_Block_withVM_moreGenes_novEdit_cdnaFIX_2fit.RData")
```



```{r, echo=F, include = F}
m1 = plotMDS(y, labels = y$samples$samples)$cmdscale.out
df <- data.frame(dim1 = m1[,1], dim2 = m1[,2])
label = y$samples$samples
m3 <- plotMDS(y, dim.plot=c(1,3), labels = y$samples$samples)
```

3D plot
```{r, echo=FALSE}
m3cmds = m3$cmdscale.out
par3d(cex=1)
plot3d(x = m3cmds[,1], y = m3cmds[,2], z = m3cmds[,3], xlab = "1", ylab = "2", zlab = "3", 
       col = tissue.colors[cond_forplots_fix], type="p", size=8)
text3d( x = m3cmds[,1], y = m3cmds[,2], z = m3cmds[,3],cex = 0.8, font = 1, text = y$samples$samples, 
        adj = 2, color=gender.colors[gender], family="sans") 

subid <- currentSubscene3d()
rglwidget(elementId="3DMDS")
```
